### ISSUE TITLE
oc login difference

### ISSUE THREAD

**Issue by maxandersen** [redhat-actions/oc-login#3] opened 2020-12-10 23:35 UTC
I just noticed that:

```
oc login --token=<token> --server=<server>
```

sets a namespace in kubeconfig.

but:
```
 - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1

        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
```

does not.

Resulting in different behavior - and in case of openshift sandbox it means oc login works and I can deploy, but oc login with github action I end up in the wrong place.

Workaround is to set namespace explicitly but I would expect the two would/should behave the same ?

**Comment by tetchel** [comment] 2020-12-11 01:34
Hi, I recall noticing the same behaviour when developing the action. I was also using the sandbox. You're right that this action should have the same behaviour as regularly invoking `oc login`, because that's all it does under the covers anyway.

This seems to be a problem specific to the sandbox, or could also be considered an `oc` problem. I believe it's because when you log into a cluster for the first time with `oc`, it tries to select the `default` project. But in the sandbox, you don't have permission to do that.

To test this, I reproduced your bug in [this workflow run](https://github.com/redhat-actions/oc-login/runs/1534503609?check_suite_focus=true) which fails to deploy to the sandbox because I don't have access to the `default` namespace. You'll notice that the `namespace` is missing from the kubeconfig printed in the `Log in and set context` step.

Then, I tried a different cluster where I have access to all namespaces in [this workflow run](https://github.com/redhat-actions/oc-login/runs/1534536776?check_suite_focus=true). I still did not have a namespace selected, but this time it succeeds. You can see the `default` namespace is added to the kubeconfig. 

So, I think the behaviour here is consistent with `oc`, and this problem is unique to clusters where you don't have access to the default project/namespace. You will have to set the namespace explicitly.

**Comment by maxandersen** [comment] 2020-12-11 06:17
But why does it work with the Same cluster with oc login ?

The Kube config  gets namespace set Afaics.

**Comment by gorkem** [comment] 2020-12-11 14:20
I was thinking about this. Perhaps the current behaviour is the right one. The oc behaviour is error prone for CI,  adding a namespace that is earlier on the alphabetical order after can cause the actions to deploy to a namespace other than intended originally.

The interactive nature of oc on CLI prevents such mistakes by showing the current selected namespace, which is not available to a workflow.

**Comment by tetchel** [comment] 2020-12-12 04:09
The problem with the current behaviour seems to be its inconsistency, since it depends on whether or not the user can access `default`.

Max, have you had a workflow run auto-select your namespace with `oc login`? Or, on your local machine? 

I also see it selecting the correct namespace on my machine, but I believe either oc or the server has cached my namespace.

**Comment by gorkem** [comment] 2020-12-12 18:11
Right. Your kubecontext is the other factor when using locally. When using on actions there is no initial kubecontext to begin with.

**Comment by tetchel** [comment] 2020-12-12 23:35
Sorry, I should have clarified, even if I delete `~/.kube/config` it still 'remembers' my namespace

**Comment by maxandersen** [comment] 2020-12-13 00:16
Removing kubeconfig and it does the same. 

Meaning it works by accident locally if you take what the cluster "copy login command" instructs and breaks it in ci. 

It's annoying but Afaics oc login does the right thing here. It sees you don't have access to default and picks the first one you do have access to. 

I would argue the oc action is better of being consistent.

**Comment by tetchel** [comment] 2020-12-14 00:33
right, I agree I'd like to replicate that behaviour, I'm just not sure how. I think the only reason oc knows which namespace to pick is because you've previously picked it manually.

All I'm doing is calling the same login command you'd copy from the console.

![image](https://user-images.githubusercontent.com/8888438/102028821-f7a42900-3d79-11eb-910d-ba03b35e9e92.png)

**Comment by tetchel** [comment] 2021-05-07 19:04
closing as wontfix unless anyone knows how this can be done

**Closed by tetchel** 2021-05-07 19:04 UTC
Labels: question
